[zh]
  title = "Zoey的程式日常"
  languageName = "中文"
  weight = 1
  languagedir = "ltr"  #文字書寫方向 ltr左向右 rtl右向左
  contentdir = "content/zh"

[en]
  title = "Zoey's daily coding"
  languageName = "EN"
  weight = 2
  languagedir = "ltr"  #文字書寫方向 ltr左向右 rtl右向左
  contentdir = "content/en"