[[main]]
  identifier = "home"
  name = "首頁"
  url = ""
  weight = 1

[[main]]
  identifier = "archive"
  name = "歸檔"
  url = "archive"
  weight = 2
  
#[[main]]
#  identifier = "about"
#  name = "關於我"
#  url = "about"
#  weight = 3

#[[main]]
#  identifier = "presentation"
#  name = "簡報"
#  url = "presentation"
#  weight = 3

#[[main]]
#  identifier = "gallery"
#  name = "圖檔"
#  url = "gallery"
#  weight = 4
    
#[[main]]
#  parent = "gallery"
#  name = "Cartoon"
#  url = "gallery/cartoon"

#[[main]]
#  parent = "gallery"
#  name = "Photo"
#  url = "gallery/photo"

#[[main]]
#  identifier = "posts"
#  name = "日誌"
#  url = "posts"
#  weight = 5

#[[main]]
#  identifier = "showcase"
#  name = "作品集"
#  url = "showcase"
#  weight = 6

#[[main]]
#  identifier = "publication"
#  name = "出版"
#  url = "publication"
#  weight = 7