enableBusuanzi = false  # if set true, total page view, total unique visitors show up in the footer.
busuanziSiteUV = false  # unique visitors (total number of visitors)
busuanziSitePV = false  # site total page view count
busuanziPagePV = false  # post view count
